name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-macos:
    runs-on: macos-13
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build with Nuitka
      run: |
        # Build with Nuitka
        nuitka --standalone --onefile --enable-plugin=no-qt --output-dir=dist src/main.py
        
        # Rename binary and create zip
        mv dist/main.bin dist/mcat.bin
        cd dist
        zip ../mcat.zip mcat.bin
        cd ..
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mcat-macOS
        path: |
          dist/mcat.bin
          mcat.zip
