name: Build Fedora App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        dnf update -y
        dnf install -y python3 python3-pip python3-devel gcc g++ make patchelf
    
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    
    - name: Build with Nuitka
      run: |
        # Build with Nuitka
        nuitka --standalone --onefile --enable-plugin=no-qt --include-data-dir=assets/fonts=assets/fonts --output-dir=dist src/main.py
        
        # Rename binary
        mv dist/main.bin mcat
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mcat-Fedora
        path: mcat