name: Build Fedora App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        dnf update -y
        dnf install -y python3 python3-pip python3-devel gcc g++ make
    
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    
    - name: Build with Nuitka
      run: |
        # Build with Nuitka
        nuitka --standalone --onefile --enable-plugin=no-qt --output-dir=dist src/main.py
        
        # Create tar.gz for easy download
        cd dist
        tar -czf ../WebScraper-Fedora.tar.gz .
        cd ..
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WebScraper-Fedora
        path: |
          dist/
          WebScraper-Fedora.tar.gz